### ISSUE TITLE
How the developers get those feedbacks

### ISSUE THREAD

**Issue by AathifMahir** [TheAlphamerc/app_feedback#1]
Is there any backend that we need to implement to get those user feedback?

**Comment by TheAlphamerc** [comment]
The library simply returns the feedback when user tap on submit button. Once you received feedback from library then you can use it according to  you need.

**Comment by AathifMahir** [comment]
> The library simply returns the feedback when user tap on submit button. Once you received feedback from library then you can use it according to  you need.

Where and how we receive the feedback from library?

**Comment by TheAlphamerc** [comment]
Below is code to launch the feedback form. When user submit the feedback you will receive it in `onSubmit` callback.
```dart
void launchAppFeedback() {
    feedbackForm.display(context,
        option: Option(
          maxRating: 10,
          ratingButtonTheme: RatingButtonThemeData.defaultTheme,
        ), onSubmit: (feedback) {
      print(feedback);
    });
  }
```

**Comment by AathifMahir** [comment]
> Below is code to launch the feedback form. When user submit the feedback you will receive it in `onSubmit` callback.
> 
> ```dart
> 
> void launchAppFeedback() {
> 
>     feedbackForm.display(context,
> 
>         option: Option(
> 
>           maxRating: 10,
> 
>           ratingButtonTheme: RatingButtonThemeData.defaultTheme,
> 
>         ), onSubmit: (feedback) {
> 
>       print(feedback);
> 
>     });
> 
>   }
> 
> ```

Got it, that means we can push those feedbacks server and etc.. with output

**Comment by TheAlphamerc** [comment]
Yeah, once you received the feedback, you can save it locally or send it to server.

**Comment by AathifMahir** [comment]
> Yeah, once you received the feedback, you can save it locally or send it to server.

got it,

by the way what's the data type of output, is it a Array or Json, etc..

**Comment by TheAlphamerc** [comment]
The output is the [`UserFeedback`](https://github.com/TheAlphamerc/app_feedback/blob/main/lib/src/model/feedback.dart) object.
